function interactiveRegVis(im1, im2, dimension)
    if dimension == 'z'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(im2, 3), ...
            'Value', 1, ...
            'SliderStep', [1/(size(im2, 3)-1), 1/(size(im2, 3)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(im2(:, :, currentSlice), ...
                   im1(:, :, currentSlice), ...
                   'falsecolor');
        title(['Slice along Z-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, im2, im1, 'z'));
    elseif dimension == 'x'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(im2, 1), ...
            'Value', 1, ...
            'SliderStep', [1/(size(im2, 1)-1), 1/(size(im2, 1)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(squeeze(im2(currentSlice, :, :)), ...
                   squeeze(im1(currentSlice, :, :)), ...
                   'falsecolor');
        title(['Slice along X-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, im2, im1, 'x'));
    elseif dimension == 'y'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(im2, 2), ...
            'Value', 1, ...
            'SliderStep', [1/(size(im2, 2)-1), 1/(size(im2, 2)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(squeeze(im2(:, currentSlice, :)), ...
                   squeeze(im1(:, currentSlice, :)), ...
                   'falsecolor');
        title(['Slice along Y-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, im2, im1, 'y'));
    else
        error('Invalid dimension input. Use ''x'', ''y'', or ''z''.');
    end
end
