function interactiveRegVis(registeredImage, fixedImage, dimension)
    if dimension == 'z'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(fixedImage, 3), ...
            'Value', 1, ...
            'SliderStep', [1/(size(fixedImage, 3)-1), 1/(size(fixedImage, 3)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(fixedImage(:, :, currentSlice), ...
                   registeredImage(:, :, currentSlice), ...
                   'falsecolor');
        title(['Slice along Z-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, fixedImage, registeredImage, 'z'));
    elseif dimension == 'x'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(fixedImage, 1), ...
            'Value', 1, ...
            'SliderStep', [1/(size(fixedImage, 1)-1), 1/(size(fixedImage, 1)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(squeeze(fixedImage(currentSlice, :, :)), ...
                   squeeze(registeredImage(currentSlice, :, :)), ...
                   'falsecolor');
        title(['Slice along X-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, fixedImage, registeredImage, 'x'));
    elseif dimension == 'y'
        figure;
        hSlider = uicontrol('Style', 'slider', ...
            'Min', 1, ...
            'Max', size(fixedImage, 2), ...
            'Value', 1, ...
            'SliderStep', [1/(size(fixedImage, 2)-1), 1/(size(fixedImage, 2)-1)], ...
            'Units', 'normalized', ...
            'Position', [0.2 0.02 0.6 0.05]);
        
        currentSlice = round(hSlider.Value);
        hAx = axes('Position', [0.1, 0.2, 0.8, 0.7]);
        imshowpair(squeeze(fixedImage(:, currentSlice, :)), ...
                   squeeze(registeredImage(:, currentSlice, :)), ...
                   'falsecolor');
        title(['Slice along Y-axis at index ', num2str(currentSlice)]);
        
        addlistener(hSlider, 'ContinuousValueChange', @(src, event) updateImage(src, hAx, fixedImage, registeredImage, 'y'));
    else
        error('Invalid dimension input. Use ''x'', ''y'', or ''z''.');
    end
end
